Feature/sljanje emailova
udomiljubimca/udomiljubimca-mailing-service pull request #4
Opened 2021-08-02 07:25 UTC by mifa43

Slanje email-ova korisnicima uz smtplib #3

2021-08-02 15:44 UTC, ognjen-it requested changes

2021-08-02 15:44 UTC, ognjen-it commented on Dockerfile
> +ENV PASSWORD ${PASSWORD}
ovde trebas da dodas i variable kao sto su: SMTP_HOST, SMTP_PORT..

2021-08-02 15:44 UTC, ognjen-it commented on docker-compose.yaml
> +      PASSWORD: ${PASSWORD}
kao i za docker file

2021-08-03 08:51 UTC, mifa43 commented on Dockerfile
> +ENV PASSWORD ${PASSWORD}
Sredjeno je.

2021-08-03 08:52 UTC, mifa43 commented on docker-compose.yaml
> +      PASSWORD: ${PASSWORD}
Uradjeno je.

2021-08-04 09:58 UTC, ognjen-it approved these changes
Odlicno!

2021-08-05 06:46 UTC, merged